services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:8081" # Map port 8081 on the host to port 8080 in the container
        depends_on:
            - redis # Ensure Redis starts before the app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        image: redis:7.0
        ports:
            - "6379:6379" # Map port 6379 on the host to port 6379 in the container
        command: ["redis-server", "--appendonly", "yes"]
